driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7
  - name: centos-8
  - name: debian-9
    run_list: apt::default
  - name: debian-10
    run_list: apt::default
  - name: fedora-latest
  - name: ubuntu-18.04
    run_list: apt::default
  - name: ubuntu-20.04
    run_list: apt::default

suites:
  - name: default
    run_list:
      - recipe[unicorn::default]
